### PR TITLE
allows overriding the Node runtime for lambda, closes #56

### LINKED ISSUE #56: Remove hardcoded NODEJS runtime
Minor nitpick, it could fallback to NODEJS_10_X in case `process.env['NODE_RUNTIME']` isn't set, because `functionProps` doesn't allow override for that https://github.com/punchcard/punchcard/blob/d0b6fe43d5e9ef5994c96929b28405bf7ca6cc45/packages/punchcard/lib/lambda/function.ts#L86-L90

Another way would to put `runtime` property before the `functionProps` spread (which is much easier and concise)

### PR DESCRIPTION
**Pull request by pocesar**
* remove "runtime" from `Omit` in `functionProps`
* defaults runtime to `lambda.Runtime.NODEJS_12_X`

### CODE REVIEW

**Comment by pocesar** [comment]
I don't know what is failing on the test, but I guess something checks for the runtime. the PR isn't complete, I need to remove the omitted 'runtime' from other places as well like executor

**Comment by sam-goodwin** [comment]
Fixes: https://github.com/punchcard/punchcard/issues/56

**Comment by sam-goodwin** [comment]
Looks like our tests use inline code to simplify which are breaking when we default to node 12. We should update the tests to use an asset.

```
FAIL test/lambda/test.function.js 
  ● Function › should install clients in context 
 
    Inline source not allowed for nodejs12.x 
 
      84 |  
      85 |     this.resource = scope.chain(scope => (props.functionProps || Build.of({})).map(functionProps => { 
    > 86 |       const lambdaFunction = new lambda.Function(scope, id, { 
         |                              ^ 
      87 |         runtime: lambda.Runtime.NODEJS_12_X, 
      88 |         ...functionProps, 
      89 |         code: Code.tryGetCode(scope) || Code.mock,
```

**Comment by pocesar** [comment]
I'm reverting changing the default runtime, just leaving the possibility to override it

**Comment by sam-goodwin** [comment]
Closed by: https://github.com/punchcard/punchcard/commit/91df5aeaeeb66609d64f8b491dac032b0094d8c4

**Pull request closed without merging**
